language: python
cache: pip
branches:
  only:
    - main
python:
  - "3.8"
install:
  - pip install scikit-learn
  - pip install pandas
  - pip install PyGithub
script:
  - python scoring.py
before_install:
  - openssl aes-256-cbc -K $encrypted_0d6d7d606fdf_key -iv $encrypted_0d6d7d606fdf_iv
    -in Test_Energies.csv.enc -out data/Test_Energies.csv -d
env:
  - secure: zHvM3VwngyUHznWEhyMWvWUmhXJk9L8OOMVGp322eBXcTvni2Y673rSw/3qwgAcbKL94luRMPvTXajvFkICVEYjm881RCFL3NeU9XhF9c7YpWhKSYRbd6As9tmThuca02BK/AB8nn9luvECttrE8KB6JVJzNv3lATMhki14vqaQzsEQMa/Hx8MBPoKplADv8zVjGytYpH3CJZ47OvC64RrRUltf4+57Z3/8EuiIt+0MVJ5dlqXuIruJIwP1Eh94lD7BR9Tze8ScBLyA0DfaoPLnibQJc9EqFvPIL5M7+1qbHcaYlvQMq9TehAInQvKHa3LTxeojgYoPoifbBL4/jaMSArf7Fw6anvIv23DP4WX3G7S3EkSRie4mYLevEWe/SX1HfkA9NI/6ZftbLL9lwQc4b6qBa8S9d6AlYUFhCNIkqedZp/IyA8fi+kaGVAUIaboPgSnaEh13RkP2qRyGT5fEGxqA2Az7i9X7piSS2uOg+D2D/CPdvpdtZ+C4r+yS+Vykc/oYhUbVeaGIm0Cdo/7YvnPHAye7d3lieu/fC//wTeQj03ryJJo70ZHv27T02ybVbAW3aiF4mopbt5Ad5i5kKKWVrLQ2wfovwCzp74W8AB5gp/d4tS0A9m0TzleVvhBHVPeJp+MetmLlQqR3BTFkbpCSI/STxBvQZOOoCzik=
