language: python
cache: pip
branches:
  only:
    - main
python:
  - "3.8"
install:
  - pip install scikit-learn
  - pip install pandas
  - pip install PyGithub
script:
  - python scoring.py
before_install:
  - openssl aes-256-cbc -K $encrypted_7733ca46354e_key -iv $encrypted_7733ca46354e_iv
    -in hidden_test_data.tar.enc -out hidden_test_data.tar -d
  - tar xvf hidden_test_data.tar
env:
  global:
    secure: RGJrGJVBu/aaJZFw5eLSdh576h2jrjwshTlW3CDn5xkBgtmqoNgStcyo/bvdE9iWyrQJZHt4dzHqAI3iiAHMr7+9qHnLLjWBA7FuuKc+k6J3ylx+Zv+A4DkCanohoaK7Pg9uP8x737Ftg01KauLg0Mc5sefIMefEuNrU1zJatBkGqbtuO023Om/tKI8xghH9CgpA/g6xKpkqFLeZxcFVVIRW7giuNzAwVHxF9Zkxuix5oafgCKNQGKyeIdIzgDDvqJdEQ6I8h1R6K+VAQamCPHOlzE/FNvKRB+roxu1t+QaR85m9e8LgNxmtnmHmmn/xVXD74szzUPwtAqk357Cj862bgHflrPHsLbFaVKNE6gWS/ZRwKOdB5gnlsokjvnFBrVnzSYpD/kqXVZ9iS5GgvsCeSItS74SQNWOf+XoapmaGSJH4EWafmLnv1yO6eayd8hZYUVlCdmtZ/ipHFrku8rRzkgV5RCbfYQfpF4ZsUE6vBTP4o53C2xrqlA4GUVBEx/a1OdcWO+vUxcAYiZm/pzbTaaYo9HtdihMQqLvuEqv+pTEIO/7X2Ufqr0gLTvGpYVZnEHJHmg/cAzXb43oG8rjqTZ2V3Q+yzkN+Rlj3osE5iXpAu27wGJcqyFpidkWpijSaXevpDzEc3dmPny+S/mzQq25FGYdT38Zo4Uv3bcg=
